services:
  # Stock Publisher (Producer)
  stock-publisher:
    image: switzerchees/stock-publisher
    container_name: stock_publisher
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    networks:
      - backend

  # RabbitMQ (Message Broker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
  frontend:


